"""
Phase 6: Package for Development Node.

Packages all deliverables for Tech Spec Agent handoff:
- 6 documentation files
- Validated code (from Google AI Studio)
- Validation report
- Quality metrics

Week 6: Complete handoff preparation and ANYON integration.
"""

import json
import zipfile
from pathlib import Path
from typing import Dict, Optional

from src.langgraph.state import DesignAgentState
from src.integration.anyon_client import AnyonClient
from src.config import settings
from src.utils.logger import get_logger

logger = get_logger(__name__)


async def create_validation_report(state: DesignAgentState) -> str:
    """
    Create comprehensive validation report.

    Includes:
    - Quality score breakdown
    - Accessibility audit results
    - Design system compliance
    - Performance metrics

    Args:
        state: Current workflow state

    Returns:
        Validation report as markdown string
    """
    validation_results = state.get("validation_results", {})
    quality_score = validation_results.get("quality_score", 0)

    report = f"""# Design Validation Report

**Job ID:** {state['job_id']}
**Date:** {state.get('created_at', 'N/A')}

## Overall Quality Score: {quality_score}/100

### Validation Results

#### Syntax Validation
- Status: {validation_results.get('syntax_check', {}).get('status', 'N/A')}
- Errors: {validation_results.get('syntax_check', {}).get('error_count', 0)}

#### TypeScript Validation
- Status: {validation_results.get('typescript_check', {}).get('status', 'N/A')}
- Type Errors: {validation_results.get('typescript_check', {}).get('error_count', 0)}

#### Tailwind CSS Validation
- Status: {validation_results.get('tailwind_check', {}).get('status', 'N/A')}
- Custom CSS Found: {validation_results.get('tailwind_check', {}).get('has_custom_css', False)}

#### Accessibility (WCAG AA)
- Status: {validation_results.get('accessibility_check', {}).get('status', 'N/A')}
- Issues: {validation_results.get('accessibility_check', {}).get('issue_count', 0)}
- Contrast Ratio: {validation_results.get('accessibility_check', {}).get('min_contrast_ratio', 'N/A')}
- Touch Targets: {validation_results.get('accessibility_check', {}).get('touch_target_violations', 0)} violations

#### Design System Compliance
- Status: {validation_results.get('design_system_check', {}).get('status', 'N/A')}
- Color Matches: {validation_results.get('design_system_check', {}).get('color_matches', 'N/A')}
- Typography Matches: {validation_results.get('design_system_check', {}).get('typography_matches', 'N/A')}

### Performance Metrics
- Bundle Size: {validation_results.get('performance', {}).get('bundle_size_kb', 'N/A')} KB
- Load Time Estimate: {validation_results.get('performance', {}).get('estimated_load_time_ms', 'N/A')} ms

### Recommendations
{chr(10).join(['- ' + rec for rec in validation_results.get('recommendations', [])])}

---
*Generated by ANYON Design Agent v{settings.app_version}*
"""

    return report


async def create_package_manifest(state: DesignAgentState, package_path: Path) -> Dict:
    """
    Create manifest file describing package contents.

    Args:
        state: Current workflow state
        package_path: Path to package directory

    Returns:
        Manifest dictionary
    """
    manifest = {
        "job_id": state["job_id"],
        "created_at": state.get("created_at"),
        "agent_version": settings.app_version,
        "quality_score": state.get("validation_results", {}).get("quality_score", 0),
        "documents": {
            "design_system": f"Design_System_v{settings.document_version}.md",
            "ux_flow": f"UX_Flow_v{settings.document_version}.md",
            "screen_specifications": f"Screen_Specifications_v{settings.document_version}.md",
            "google_ai_prompts": f"Google_AI_Studio_Prompts_v{settings.document_version}.md",
            "design_guidelines": f"Design_Guidelines_v{settings.document_version}.md",
            "open_source_recommendations": f"Open_Source_Recommendations_v{settings.document_version}.md",
        },
        "validated_code": "validated_code.tsx" if state.get("uploaded_code") else None,
        "validation_report": "validation_report.md",
        "screens_count": len(state.get("extracted_screens", [])),
        "selected_libraries_count": len(state.get("selected_open_source", [])),
        "ready_for_tech_spec": True,
    }

    return manifest


async def create_package_zip(
    package_dir: Path,
    output_path: Path,
) -> Path:
    """
    Create ZIP archive of package for easy distribution.

    Args:
        package_dir: Directory containing package files
        output_path: Path for ZIP file

    Returns:
        Path to created ZIP file
    """
    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zipf:
        for file_path in package_dir.rglob("*"):
            if file_path.is_file():
                arcname = file_path.relative_to(package_dir)
                zipf.write(file_path, arcname)

    logger.info(f"Package ZIP created: {output_path}")
    return output_path


async def upload_to_anyon(
    state: DesignAgentState,
    package_dir: Path,
) -> Optional[Dict]:
    """
    Upload package to ANYON platform via API.

    Creates/updates ticket and attaches all documents.

    Args:
        state: Current workflow state
        package_dir: Path to package directory

    Returns:
        ANYON API response or None if integration disabled
    """
    if not settings.anyon_enable_integration:
        logger.info("ANYON integration disabled, skipping upload")
        return None

    try:
        client = AnyonClient()
        job_id = state["job_id"]
        ticket_id = state.get("anyon_ticket_id")

        if not ticket_id:
            logger.warning("No ANYON ticket ID found, cannot upload")
            return None

        # Prepare document paths
        documents = {}
        generated_docs = state.get("generated_documents", {})

        for doc_type, file_path_str in generated_docs.items():
            file_path = Path(file_path_str)
            if file_path.exists():
                documents[doc_type] = file_path

        # Mark ticket complete and attach documents
        quality_score = state.get("validation_results", {}).get("quality_score", 0)
        response = await client.complete_design_ticket(
            ticket_id=ticket_id,
            job_id=job_id,
            quality_score=quality_score,
            documents=documents,
        )

        logger.info(
            "Package uploaded to ANYON",
            ticket_id=ticket_id,
            job_id=job_id,
        )

        return response

    except Exception as e:
        logger.error(f"Failed to upload to ANYON: {e}")
        return {"error": str(e)}


async def package_for_dev(state: DesignAgentState) -> DesignAgentState:
    """
    Phase 6 (Final): Package all deliverables for Tech Spec Agent.

    Creates comprehensive package containing:
    1. 6 documentation files
    2. Validated code (if uploaded)
    3. Validation report
    4. Package manifest (JSON)
    5. ZIP archive for distribution

    Optional: Uploads to ANYON platform if integration enabled.

    Updates state:
    - package_path: Path to packaged deliverables
    - package_zip_path: Path to ZIP archive
    - anyon_upload_status: Status of ANYON upload
    - current_phase: 6 (Complete)
    - status: "completed"

    Args:
        state: Current workflow state

    Returns:
        Updated state with package information
    """
    logger.info("=== Phase 6 (Final): Packaging for Development ===", job_id=state["job_id"])

    try:
        job_id = state["job_id"]
        package_dir = Path(f"docs/generated_outputs/{job_id}/package")
        package_dir.mkdir(parents=True, exist_ok=True)

        # 1. Copy all generated documents
        logger.info("Copying generated documents...", job_id=job_id)
        generated_docs = state.get("generated_documents", {})

        for doc_type, file_path_str in generated_docs.items():
            source_path = Path(file_path_str)
            if source_path.exists():
                dest_path = package_dir / source_path.name
                dest_path.write_text(source_path.read_text(encoding="utf-8"), encoding="utf-8")
                logger.debug(f"Copied: {source_path.name}", job_id=job_id)

        # 2. Copy validated code (if exists)
        if state.get("uploaded_code"):
            logger.info("Adding validated code...", job_id=job_id)
            code_path = package_dir / "validated_code.tsx"
            code_path.write_text(state["uploaded_code"], encoding="utf-8")

        # 3. Generate and save validation report
        logger.info("Generating validation report...", job_id=job_id)
        validation_report = await create_validation_report(state)
        report_path = package_dir / "validation_report.md"
        report_path.write_text(validation_report, encoding="utf-8")

        # 4. Create package manifest
        logger.info("Creating package manifest...", job_id=job_id)
        manifest = await create_package_manifest(state, package_dir)
        manifest_path = package_dir / "manifest.json"
        manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

        # 5. Create ZIP archive
        logger.info("Creating ZIP archive...", job_id=job_id)
        zip_path = Path(f"docs/generated_outputs/{job_id}/design_package_{job_id}.zip")
        await create_package_zip(package_dir, zip_path)

        # 6. Upload to ANYON (if enabled)
        anyon_status = None
        if settings.anyon_enable_integration:
            logger.info("Uploading to ANYON platform...", job_id=job_id)
            anyon_status = await upload_to_anyon(state, package_dir)

        logger.info(
            "✅ Phase 6 complete: Package ready for Tech Spec Agent",
            job_id=job_id,
            package_dir=str(package_dir),
            zip_path=str(zip_path),
        )

        return {
            **state,
            "package_path": str(package_dir),
            "package_zip_path": str(zip_path),
            "anyon_upload_status": anyon_status,
            "current_phase": 6,
            "phase_name": "Complete",
            "status": "completed",
        }

    except Exception as e:
        logger.error(f"Packaging failed: {e}", job_id=state["job_id"])
        return {
            **state,
            "error": f"Packaging failed: {str(e)}",
            "current_phase": 6,
            "phase_name": "Packaging (Failed)",
            "status": "failed",
        }


__all__ = ["package_for_dev"]
